name: Build and Release ELF

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install build tools
        run: |
          sudo apt update
          sudo apt install -y build-essential gcc-arm-none-eabi

      - name: Build project
        run: make

      - name: Upload .elf to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./*.elf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}