name: Code Quality and Build

on: [push, pull_request]

jobs:

  cppcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update apt and install cppcheck
        run: |
          sudo apt update
          sudo apt install -y cppcheck

      - name: Analyze src files
        run: cppcheck src -q --check-level=exhaustive --enable=all --checkers-report=cppcheck_output_report.txt --output-file=cppcheck_output.txt

      - name: Upload the cppcheckout_report file
        uses: actions/upload-artifact@v4
        with:
          name: cppcheck-report
          path: ./cppcheck_output_report.txt

      - name: Upload the cppcheckout file
        uses: actions/upload-artifact@v4
        with:
          name: cppcheck
          path: ./cppcheck_output.txt


  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update apt and install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential gcc-arm-none-eabi

      - name: Build the project
        run: make

      - name: Upload .elf artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware-elf
          path: ./*.elf